/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`public_holidays_by_date_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PublicHolidaysByDateGetError {
    Status400(models::ProblemDetails),
    Status500(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`public_holidays_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PublicHolidaysGetError {
    Status400(models::ProblemDetails),
    Status500(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`school_holidays_by_date_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SchoolHolidaysByDateGetError {
    Status400(models::ProblemDetails),
    Status500(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`school_holidays_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SchoolHolidaysGetError {
    Status400(models::ProblemDetails),
    Status500(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}


pub async fn public_holidays_by_date_get(configuration: &configuration::Configuration, date: chrono::NaiveDate, language_iso_code: Option<&str>) -> Result<Vec<models::HolidayByDateResponse>, Error<PublicHolidaysByDateGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_date = date;
    let p_language_iso_code = language_iso_code;

    let uri_str = format!("{}/PublicHolidaysByDate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("date", &p_date.to_string())]);
    if let Some(ref param_value) = p_language_iso_code {
        req_builder = req_builder.query(&[("languageIsoCode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::HolidayByDateResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::HolidayByDateResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PublicHolidaysByDateGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn public_holidays_get(configuration: &configuration::Configuration, country_iso_code: &str, valid_from: chrono::NaiveDate, valid_to: chrono::NaiveDate, language_iso_code: Option<&str>, subdivision_code: Option<&str>) -> Result<Vec<models::HolidayResponse>, Error<PublicHolidaysGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_country_iso_code = country_iso_code;
    let p_valid_from = valid_from;
    let p_valid_to = valid_to;
    let p_language_iso_code = language_iso_code;
    let p_subdivision_code = subdivision_code;

    let uri_str = format!("{}/PublicHolidays", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryIsoCode", &p_country_iso_code.to_string())]);
    req_builder = req_builder.query(&[("validFrom", &p_valid_from.to_string())]);
    req_builder = req_builder.query(&[("validTo", &p_valid_to.to_string())]);
    if let Some(ref param_value) = p_language_iso_code {
        req_builder = req_builder.query(&[("languageIsoCode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_subdivision_code {
        req_builder = req_builder.query(&[("subdivisionCode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::HolidayResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::HolidayResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PublicHolidaysGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn school_holidays_by_date_get(configuration: &configuration::Configuration, date: chrono::NaiveDate, language_iso_code: Option<&str>) -> Result<Vec<models::HolidayByDateResponse>, Error<SchoolHolidaysByDateGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_date = date;
    let p_language_iso_code = language_iso_code;

    let uri_str = format!("{}/SchoolHolidaysByDate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("date", &p_date.to_string())]);
    if let Some(ref param_value) = p_language_iso_code {
        req_builder = req_builder.query(&[("languageIsoCode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::HolidayByDateResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::HolidayByDateResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SchoolHolidaysByDateGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn school_holidays_get(configuration: &configuration::Configuration, country_iso_code: &str, valid_from: chrono::NaiveDate, valid_to: chrono::NaiveDate, language_iso_code: Option<&str>, subdivision_code: Option<&str>) -> Result<Vec<models::HolidayResponse>, Error<SchoolHolidaysGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_country_iso_code = country_iso_code;
    let p_valid_from = valid_from;
    let p_valid_to = valid_to;
    let p_language_iso_code = language_iso_code;
    let p_subdivision_code = subdivision_code;

    let uri_str = format!("{}/SchoolHolidays", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryIsoCode", &p_country_iso_code.to_string())]);
    req_builder = req_builder.query(&[("validFrom", &p_valid_from.to_string())]);
    req_builder = req_builder.query(&[("validTo", &p_valid_to.to_string())]);
    if let Some(ref param_value) = p_language_iso_code {
        req_builder = req_builder.query(&[("languageIsoCode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_subdivision_code {
        req_builder = req_builder.query(&[("subdivisionCode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::HolidayResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::HolidayResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SchoolHolidaysGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

