//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::allocated_resource::Entity as AllocatedResource;
pub use super::allocation::Entity as Allocation;
pub use super::availability::Entity as Availability;
pub use super::booking::Entity as Booking;
pub use super::booking_resource::Entity as BookingResource;
pub use super::dependency::Entity as Dependency;
pub use super::holiday::Entity as Holiday;
pub use super::holiday_entry::Entity as HolidayEntry;
pub use super::issue::Entity as Issue;
pub use super::resource_constraint::Entity as ResourceConstraint;
pub use super::resource_constraint_entry::Entity as ResourceConstraintEntry;
pub use super::resource_header::Entity as ResourceHeader;
pub use super::resource_iteration::Entity as ResourceIteration;
pub use super::revision::Entity as Revision;
pub use super::task_header::Entity as TaskHeader;
pub use super::task_iteration::Entity as TaskIteration;
pub use super::vacation::Entity as Vacation;
