//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "resource_iteration"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub timezone: String,
    pub added: DateTimeUtc,
    pub removed: Option<DateTimeUtc>,
    pub holiday_id: Option<i32>,
    pub header_id: i32,
    pub rev_created: i64,
    pub rev_deleted: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Timezone,
    Added,
    Removed,
    HolidayId,
    HeaderId,
    RevCreated,
    RevDeleted,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Holiday,
    ResourceHeader,
    Revision2,
    Revision1,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Timezone => ColumnType::String(StringLen::None).def(),
            Self::Added => ColumnType::Timestamp.def(),
            Self::Removed => ColumnType::Timestamp.def().null(),
            Self::HolidayId => ColumnType::Integer.def().null(),
            Self::HeaderId => ColumnType::Integer.def(),
            Self::RevCreated => ColumnType::BigInteger.def(),
            Self::RevDeleted => ColumnType::BigInteger.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Holiday => Entity::belongs_to(super::holiday::Entity)
                .from(Column::HolidayId)
                .to(super::holiday::Column::Id)
                .into(),
            Self::ResourceHeader => Entity::belongs_to(super::resource_header::Entity)
                .from(Column::HeaderId)
                .to(super::resource_header::Column::Id)
                .into(),
            Self::Revision2 => Entity::belongs_to(super::revision::Entity)
                .from(Column::RevDeleted)
                .to(super::revision::Column::Id)
                .into(),
            Self::Revision1 => Entity::belongs_to(super::revision::Entity)
                .from(Column::RevCreated)
                .to(super::revision::Column::Id)
                .into(),
        }
    }
}

impl Related<super::holiday::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Holiday.def()
    }
}

impl Related<super::resource_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceHeader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
