//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "allocation"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub task_id: i32,
    pub start: DateTimeUtc,
    pub end: DateTimeUtc,
    pub allocation_type: String,
    pub r#final: bool,
    pub revision: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    TaskId,
    Start,
    End,
    AllocationType,
    Final,
    Revision,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AllocatedResource,
    TaskIteration,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::TaskId => ColumnType::Integer.def(),
            Self::Start => ColumnType::Timestamp.def(),
            Self::End => ColumnType::Timestamp.def(),
            Self::AllocationType => ColumnType::String(StringLen::None).def(),
            Self::Final => ColumnType::Boolean.def(),
            Self::Revision => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AllocatedResource => Entity::has_many(super::allocated_resource::Entity).into(),
            Self::TaskIteration => Entity::belongs_to(super::task_iteration::Entity)
                .from(Column::TaskId)
                .to(super::task_iteration::Column::Id)
                .into(),
        }
    }
}

impl Related<super::allocated_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AllocatedResource.def()
    }
}

impl Related<super::task_iteration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskIteration.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
