//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "allocated_resource")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub allocation_id: i32,
    pub resource_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::allocation::Entity",
        from = "Column::AllocationId",
        to = "super::allocation::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Allocation,
    #[sea_orm(
        belongs_to = "super::resource::Entity",
        from = "Column::ResourceId",
        to = "super::resource::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Resource,
}

impl Related<super::allocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Allocation.def()
    }
}

impl Related<super::resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Resource.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
