//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "availability"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub resource_id: i32,
    pub weekday: String,
    pub duration: Decimal,
    pub rev_created: u64,
    pub rev_deleted: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ResourceId,
    Weekday,
    Duration,
    RevCreated,
    RevDeleted,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ResourceIteration,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::ResourceId => ColumnType::Integer.def(),
            Self::Weekday => ColumnType::String(StringLen::N(2u32)).def(),
            Self::Duration => ColumnType::Decimal(None).def(),
            Self::RevCreated => ColumnType::BigUnsigned.def(),
            Self::RevDeleted => ColumnType::BigUnsigned.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ResourceIteration => Entity::belongs_to(super::resource_iteration::Entity)
                .from(Column::ResourceId)
                .to(super::resource_iteration::Column::Id)
                .into(),
        }
    }
}

impl Related<super::resource_iteration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceIteration.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
