//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "holiday"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub external_id: String,
    pub name: String,
    pub start: Option<Date>,
    pub end: Option<Date>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ExternalId,
    Name,
    Start,
    End,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    HolidayEntry,
    ResourceIteration,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::ExternalId => ColumnType::String(StringLen::None).def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Start => ColumnType::Date.def().null(),
            Self::End => ColumnType::Date.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::HolidayEntry => Entity::has_many(super::holiday_entry::Entity).into(),
            Self::ResourceIteration => Entity::has_many(super::resource_iteration::Entity).into(),
        }
    }
}

impl Related<super::holiday_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HolidayEntry.def()
    }
}

impl Related<super::resource_iteration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceIteration.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
