//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "holiday_entry"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub holiday_id: i32,
    pub name: Option<String>,
    pub date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    HolidayId,
    Name,
    Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Holiday,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::HolidayId => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def().null(),
            Self::Date => ColumnType::Date.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Holiday => Entity::belongs_to(super::holiday::Entity)
                .from(Column::HolidayId)
                .to(super::holiday::Column::Id)
                .into(),
        }
    }
}

impl Related<super::holiday::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Holiday.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
