//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "issue"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub code: i32,
    pub description: String,
    pub r#type: String,
    pub task_id: Option<i32>,
    pub rev_created: i64,
    pub rev_deleted: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Code,
    Description,
    Type,
    TaskId,
    RevCreated,
    RevDeleted,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Revision2,
    Revision1,
    TaskHeader,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Code => ColumnType::Integer.def(),
            Self::Description => ColumnType::String(StringLen::None).def(),
            Self::Type => ColumnType::String(StringLen::None).def(),
            Self::TaskId => ColumnType::Integer.def().null(),
            Self::RevCreated => ColumnType::BigInteger.def(),
            Self::RevDeleted => ColumnType::BigInteger.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Revision2 => Entity::belongs_to(super::revision::Entity)
                .from(Column::RevDeleted)
                .to(super::revision::Column::Id)
                .into(),
            Self::Revision1 => Entity::belongs_to(super::revision::Entity)
                .from(Column::RevCreated)
                .to(super::revision::Column::Id)
                .into(),
            Self::TaskHeader => Entity::belongs_to(super::task_header::Entity)
                .from(Column::TaskId)
                .to(super::task_header::Column::Id)
                .into(),
        }
    }
}

impl Related<super::task_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskHeader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
