//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod allocated_resource;
pub mod allocation;
pub mod availability;
pub mod booking;
pub mod booking_resource;
pub mod dependency;
pub mod holiday;
pub mod holiday_entry;
pub mod issue;
pub mod resource_constraint;
pub mod resource_constraint_entry;
pub mod resource_header;
pub mod resource_iteration;
pub mod revision;
pub mod task_header;
pub mod task_iteration;
pub mod vacation;
