//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::allocated_resource::Entity as AllocatedResource;
pub use super::allocation::Entity as Allocation;
pub use super::resource::Entity as Resource;
pub use super::resource_constraint::Entity as ResourceConstraint;
pub use super::resource_constraint_entry::Entity as ResourceConstraintEntry;
pub use super::task::Entity as Task;
