//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "resource"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub timezone: String,
    pub added: DateTimeUtc,
    pub removed: Option<DateTimeUtc>,
    pub holiday_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Timezone,
    Added,
    Removed,
    HolidayId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AllocatedResource,
    Availability,
    Holiday,
    ResourceConstraintEntry,
    Vacation,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Timezone => ColumnType::String(StringLen::None).def(),
            Self::Added => ColumnType::Timestamp.def(),
            Self::Removed => ColumnType::Timestamp.def().null(),
            Self::HolidayId => ColumnType::Integer.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AllocatedResource => Entity::has_many(super::allocated_resource::Entity).into(),
            Self::Availability => Entity::has_many(super::availability::Entity).into(),
            Self::Holiday => Entity::belongs_to(super::holiday::Entity)
                .from(Column::HolidayId)
                .to(super::holiday::Column::Id)
                .into(),
            Self::ResourceConstraintEntry => {
                Entity::has_many(super::resource_constraint_entry::Entity).into()
            }
            Self::Vacation => Entity::has_many(super::vacation::Entity).into(),
        }
    }
}

impl Related<super::allocated_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AllocatedResource.def()
    }
}

impl Related<super::availability::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Availability.def()
    }
}

impl Related<super::holiday::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Holiday.def()
    }
}

impl Related<super::resource_constraint_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceConstraintEntry.def()
    }
}

impl Related<super::vacation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vacation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
