//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "resource")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub availability: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::allocated_resource::Entity")]
    AllocatedResource,
    #[sea_orm(has_many = "super::resource_constraint::Entity")]
    ResourceConstraint,
    #[sea_orm(has_many = "super::resource_constraint_entry::Entity")]
    ResourceConstraintEntry,
}

impl Related<super::allocated_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AllocatedResource.def()
    }
}

impl Related<super::resource_constraint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceConstraint.def()
    }
}

impl Related<super::resource_constraint_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceConstraintEntry.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
