//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "resource_constraint_entry"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub resource_constraint_id: i32,
    pub resource_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ResourceConstraintId,
    ResourceId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Resource,
    ResourceConstraint,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::ResourceConstraintId => ColumnType::Integer.def(),
            Self::ResourceId => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Resource => Entity::belongs_to(super::resource::Entity)
                .from(Column::ResourceId)
                .to(super::resource::Column::Id)
                .into(),
            Self::ResourceConstraint => Entity::belongs_to(super::resource_constraint::Entity)
                .from(Column::ResourceConstraintId)
                .to(super::resource_constraint::Column::Id)
                .into(),
        }
    }
}

impl Related<super::resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Resource.def()
    }
}

impl Related<super::resource_constraint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceConstraint.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
