//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "resource_header"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub rev_created: i64,
    pub rev_deleted: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RevCreated,
    RevDeleted,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AllocatedResource,
    Availability,
    BookingResource,
    ResourceConstraintEntry,
    ResourceIteration,
    Revision2,
    Revision1,
    Vacation,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::RevCreated => ColumnType::BigInteger.def(),
            Self::RevDeleted => ColumnType::BigInteger.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AllocatedResource => Entity::has_many(super::allocated_resource::Entity).into(),
            Self::Availability => Entity::has_many(super::availability::Entity).into(),
            Self::BookingResource => Entity::has_many(super::booking_resource::Entity).into(),
            Self::ResourceConstraintEntry => {
                Entity::has_many(super::resource_constraint_entry::Entity).into()
            }
            Self::ResourceIteration => Entity::has_many(super::resource_iteration::Entity).into(),
            Self::Revision2 => Entity::belongs_to(super::revision::Entity)
                .from(Column::RevDeleted)
                .to(super::revision::Column::Id)
                .into(),
            Self::Revision1 => Entity::belongs_to(super::revision::Entity)
                .from(Column::RevCreated)
                .to(super::revision::Column::Id)
                .into(),
            Self::Vacation => Entity::has_many(super::vacation::Entity).into(),
        }
    }
}

impl Related<super::allocated_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AllocatedResource.def()
    }
}

impl Related<super::availability::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Availability.def()
    }
}

impl Related<super::booking_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookingResource.def()
    }
}

impl Related<super::resource_constraint_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceConstraintEntry.def()
    }
}

impl Related<super::resource_iteration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceIteration.def()
    }
}

impl Related<super::vacation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vacation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
