//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "resource_constraint")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub task_id: i32,
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::resource::Entity",
        from = "Column::TaskId",
        to = "super::resource::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Resource,
    #[sea_orm(has_many = "super::resource_constraint_entry::Entity")]
    ResourceConstraintEntry,
}

impl Related<super::resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Resource.def()
    }
}

impl Related<super::resource_constraint_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceConstraintEntry.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
