//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "task"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub parent_id: Option<i32>,
    pub title: String,
    pub description: String,
    pub designation: String,
    pub earliest_start: Option<DateTimeUtc>,
    pub schedule_target: Option<DateTimeUtc>,
    pub effort: Option<f32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ParentId,
    Title,
    Description,
    Designation,
    EarliestStart,
    ScheduleTarget,
    Effort,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Allocation,
    SelfRef,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::ParentId => ColumnType::Integer.def().null(),
            Self::Title => ColumnType::String(StringLen::None).def(),
            Self::Description => ColumnType::String(StringLen::None).def(),
            Self::Designation => ColumnType::String(StringLen::None).def(),
            Self::EarliestStart => ColumnType::Timestamp.def().null(),
            Self::ScheduleTarget => ColumnType::Timestamp.def().null(),
            Self::Effort => ColumnType::Float.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Allocation => Entity::has_many(super::allocation::Entity).into(),
            Self::SelfRef => Entity::belongs_to(Entity)
                .from(Column::ParentId)
                .to(Column::Id)
                .into(),
        }
    }
}

impl Related<super::allocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Allocation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
