/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CountryReference : Representation of a country reference
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CountryReference {
    /// Country ISO code
    #[serde(rename = "isoCode")]
    pub iso_code: String,
}

impl CountryReference {
    /// Representation of a country reference
    pub fn new(iso_code: String) -> CountryReference {
        CountryReference {
            iso_code,
        }
    }
}

