/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HolidayByDateResponse : Representation of a holiday by date
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HolidayByDateResponse {
    /// Additional localized comments
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<Vec<models::LocalizedText>>>,
    #[serde(rename = "country")]
    pub country: Box<models::CountryReference>,
    /// Unqiue holiday id
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Localized names of the holiday
    #[serde(rename = "name")]
    pub name: Vec<models::LocalizedText>,
    /// Is the holiday nationwide?
    #[serde(rename = "nationwide")]
    pub nationwide: bool,
    #[serde(rename = "regionalScope", skip_serializing_if = "Option::is_none")]
    pub regional_scope: Option<models::RegionalScope>,
    /// List of subdivision references
    #[serde(rename = "subdivisions", skip_serializing_if = "Option::is_none")]
    pub subdivisions: Option<Vec<models::SubdivisionReference>>,
    #[serde(rename = "temporalScope", skip_serializing_if = "Option::is_none")]
    pub temporal_scope: Option<models::TemporalScope>,
    #[serde(rename = "type")]
    pub r#type: models::HolidayType,
}

impl HolidayByDateResponse {
    /// Representation of a holiday by date
    pub fn new(country: models::CountryReference, id: uuid::Uuid, name: Vec<models::LocalizedText>, nationwide: bool, r#type: models::HolidayType) -> HolidayByDateResponse {
        HolidayByDateResponse {
            comment: None,
            country: Box::new(country),
            id,
            name,
            nationwide,
            regional_scope: None,
            subdivisions: None,
            temporal_scope: None,
            r#type,
        }
    }
}

