/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LanguageResponse : Representation of a language as defined in ISO-639-1
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LanguageResponse {
    /// ISO-639-1 language code
    #[serde(rename = "isoCode")]
    pub iso_code: String,
    /// Localized language names
    #[serde(rename = "name")]
    pub name: Vec<models::LocalizedText>,
}

impl LanguageResponse {
    /// Representation of a language as defined in ISO-639-1
    pub fn new(iso_code: String, name: Vec<models::LocalizedText>) -> LanguageResponse {
        LanguageResponse {
            iso_code,
            name,
        }
    }
}

