/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LocalizedText : A localized text string
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalizedText {
    /// ISO-639-1 language code
    #[serde(rename = "language")]
    pub language: String,
    /// The localized text
    #[serde(rename = "text")]
    pub text: String,
}

impl LocalizedText {
    /// A localized text string
    pub fn new(language: String, text: String) -> LocalizedText {
        LocalizedText {
            language,
            text,
        }
    }
}

