/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegionalScope : Regional scope of a holdiay
/// Regional scope of a holdiay
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegionalScope {
    #[serde(rename = "National")]
    National,
    #[serde(rename = "Regional")]
    Regional,
    #[serde(rename = "Local")]
    Local,

}

impl std::fmt::Display for RegionalScope {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::National => write!(f, "National"),
            Self::Regional => write!(f, "Regional"),
            Self::Local => write!(f, "Local"),
        }
    }
}

impl Default for RegionalScope {
    fn default() -> RegionalScope {
        Self::National
    }
}

