/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubdivisionReference : Representation of a subdivision reference
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubdivisionReference {
    /// Subdivision code
    #[serde(rename = "code")]
    pub code: String,
    /// Short name for display
    #[serde(rename = "shortName")]
    pub short_name: String,
}

impl SubdivisionReference {
    /// Representation of a subdivision reference
    pub fn new(code: String, short_name: String) -> SubdivisionReference {
        SubdivisionReference {
            code,
            short_name,
        }
    }
}

