/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TemporalScope : Temporal scope of a holdiay
/// Temporal scope of a holdiay
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TemporalScope {
    #[serde(rename = "FullDay")]
    FullDay,
    #[serde(rename = "HalfDay")]
    HalfDay,

}

impl std::fmt::Display for TemporalScope {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FullDay => write!(f, "FullDay"),
            Self::HalfDay => write!(f, "HalfDay"),
        }
    }
}

impl Default for TemporalScope {
    fn default() -> TemporalScope {
        Self::FullDay
    }
}

