schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

enum AllocationType {
  PLAN
  BOOKING
}

enum CalculationState {
  MODIFIED
  CALCULATING
  FINISHED
}

enum IssueCode {
  PRED_ISSUE
  REQUIREMENT_MISSING
  MILESTONE_MISSING
  RESOURCE_MISSING
  NO_EFFORT
  NO_SLOT_FOUND
  DEPENDENCY_LOOP
  HIERARCHY_LOOP
  UNKNOWN
}

enum IssueType {
  TASK
  PLANNING_TASK
  PLANNING_GENERAL
  GENERAL
}

enum TaskDesignation {
  TASK
  GROUP
  REQUIREMENT
  MILESTONE
}

enum Weekday {
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
  SUNDAY
}

input AvailabilityInput {
  weekday: Weekday!
  duration: Int!
}

input ResourceConstraintEntryInput {
  resourceId: Int!
}

input ResourceConstraintInput {
  optional: Boolean!
  speed: Float!
  entries: [ResourceConstraintEntryInput!]!
}

input ResourceSaveInput {
  dbId: Int
  name: String!
  timezone: String!
  added: DateTime!
  removed: DateTime
  holidayId: Int
  availability: [AvailabilityInput!]
  addedVacations: [VacationInput!]
  removedVacations: [Int!]
}

input TaskSaveInput {
  dbId: Int
  title: String!
  description: String!
  designation: TaskDesignation!
  parentId: Int
  earliestStart: DateTime
  scheduleTarget: DateTime
  effort: Float
  priority: Float!
  predecessors: [Int!]
  successors: [Int!]
  children: [Int!]
  resourceConstraints: [ResourceConstraintInput!]
}

input VacationInput {
  from: DateTime!
  until: DateTime!
}

"""
  Combined date and time (with time zone) in [RFC 3339][0] format.

  Represents a description of an exact instant on the time-line (such as the
  instant that a user account was created).

  [`DateTime` scalar][1] compliant.

  See also [`chrono::DateTime`][2] for details.

  [0]: https://datatracker.ietf.org/doc/html/rfc3339#section-5
  [1]: https://graphql-scalars.dev/docs/scalars/date-time
  [2]: https://docs.rs/chrono/latest/chrono/struct.DateTime.html
"""
scalar DateTime

scalar Int64

"""
  Date in the proleptic Gregorian calendar (without time zone).

  Represents a description of the date (as used for birthdays, for example).
  It cannot represent an instant on the time-line.

  [`LocalDate` scalar][1] compliant.

  See also [`chrono::NaiveDate`][2] for details.

  [1]: https://graphql-scalars.dev/docs/scalars/local-date
  [2]: https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDate.html
"""
scalar LocalDate

type Allocation {
  dbId: Int!
  start: DateTime!
  end: DateTime!
  allocationType: AllocationType!
  final: Boolean!
  resources: [Resource!]!
  task: Task!
}

type Availability {
  dbId: Int!
  resource: Resource!
  duration: Int!
  weekday: Weekday!
}

type Booking {
  dbId: Int!
  start: DateTime!
  end: DateTime!
  final: Boolean!
  resources: [Resource!]!
  task: Task!
}

type CalculationUpdate {
  state: CalculationState!
  plan: Plan
}

type Country {
  isocode: String!
  name: String!
  regions: [Region!]!
}

type Holiday {
  dbId: Int!
  externalId: String!
  name: String!
  country: Country
  region: Region
  entries(from: LocalDate!, until: LocalDate!): [HolidayEntry!]!
}

type HolidayEntry {
  dbId: Int!
  date: LocalDate!
  name: String
  holiday: Holiday!
}

type Interval {
  start: DateTime!
  end: DateTime!
}

type Issue {
  dbId: Int!
  code: IssueCode!
  description: String!
  type: IssueType!
  task: Task
}

type Mutation {
  new: Mutation!
  taskSave(task: TaskSaveInput!): Task!
  taskDelete(taskId: Int!): Boolean!
  resourceSave(resource: ResourceSaveInput!): Resource!
  resourceDelete(resourceId: Int!): Boolean!
  bookingSave(dbId: Int, taskId: Int!, start: DateTime!, end: DateTime!, resources: [Int!]!, final: Boolean!): Booking!
  bookingDelete(dbId: Int!): Boolean!
  "Trigger a manual recalculation now"
  recalculateNow: Boolean!
}

type Plan {
  allocations: [Allocation!]!
}

type Query {
  helloWorld: String!
  tasks(revision: Int64): [Task!]!
  resources(revision: Int64): [Resource!]!
  countries: [Country!]!
  country(isocode: String!): Country
  region(isocode: String!): Region
  getFromOpenHolidays(isocode: String!): Holiday
  currentPlan(revision: Int64): Plan!
  bookings(revision: Int64): [Booking!]!
  issues(revision: Int64): [Issue!]!
}

type Region {
  isocode: String!
  name: String!
  countryName: String!
  regionName: String!
  holiday: Holiday!
  country: Country!
}

type Resource {
  dbId: Int!
  name: String!
  timezone: String!
  added: DateTime!
  removed: DateTime
  holiday: Holiday
  availability: [Availability!]!
  vacation: [Vacation!]!
  combinedAvailability(start: DateTime!, end: DateTime!): [Interval!]!
}

type ResourceConstraint {
  id: Int!
  optional: Boolean!
  speed: Float!
  entries: [ResourceConstraintEntry!]!
}

type ResourceConstraintEntry {
  id: Int!
  resource: Resource!
}

type Subscription {
  apiVersion: String!
  calculationUpdate: CalculationUpdate!
}

type Task {
  dbId: Int!
  title: String!
  description: String!
  earliestStart: DateTime
  scheduleTarget: DateTime
  effort: Float
  priority: Float!
  designation: TaskDesignation!
  predecessors: [Task!]!
  successors: [Task!]!
  children: [Task!]!
  issues: [Issue!]!
  parent: Task
  resourceConstraints: [ResourceConstraint!]!
  allocations: [Allocation!]!
}

type Vacation {
  dbId: Int!
  from: DateTime!
  until: DateTime!
}
